name: bookzy
description: Bookzy is a platform to get access to various book, access to read & listen to different books in boklists arranged for various users

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hexcolor: ^2.0.3
  fancy_bar: ^1.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
    - family: Suravaram
      fonts:
        - asset: fonts/Suravaram-Regular.ttf

